version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    commit-message:
      prefix: ci
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: '05:00'
    allow:
      - dependency-type: production
    ignore:
      - dependency-name: node-fetch
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: build
      include: scope
