style: github
template: RELEASENOTES.tpl.md
info:
  title: Changelog
  repository_url: https://github.com/teatimeguest/setup-texlive-action
options:
  tag_filter_pattern: v*.*.*
  sort: semver
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
