[changelog]
header = ""
body = """
{%- if version %}
  {{- version }}

  ### Full Commit SHA

  ```sha1
  {{ commit_id }}
  ```
  {% for commit in commits | filter(attribute="breaking", value=true) -%}
    {%- if loop.first %}
      ### BREAKING CHANGES

    {% endif -%}
    - {{ commit.breaking_description }}
  {% endfor -%}
  {%
    for group in [
      "Features",
      "Bug Fixes",
      "Performance Improvements",
      "Dependency Updates",
    ]
  -%}
    {%
      for commit in commits |
      filter(attribute="group", value=group) |
      sort(attribute="scope")
    -%}
      {%- if loop.first %}
        ### {{ group }}

      {% endif -%}
      - {% if commit.scope != "" -%}
          **{{ commit.scope ~ ":" }}**{{ " " }}
        {%- endif -%}
        {{ commit.message }}
    {% endfor -%}
  {% endfor %}
{% endif -%}
"""
footer = ""
trim = true

[git]
conventional_commits = true
commit_preprocessors = [
  { pattern = "\\s*\\[skip ci\\]", replace = "" },
]
commit_parsers = [
  { message = "^feat", group = "Features", default_scope = "" },
  { message = "^fix\\(unreleased\\)", skip = true },
  { message = "^fix", group = "Bug Fixes", default_scope = "" },
  { message = "^perf", group = "Performance Improvements", default_scope = "" },
  { message = "^build\\(deps\\)", group = "Dependency Updates", scope = "" },
]
protect_breaking_commits = true
filter_commits = true
tag_pattern = "v*.*.*"
