name: CI

on:
  push:
    branches: '**'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Check format
        run: |
          npm run format-check
          npm run editorconfig-checker

      - name: Test
        run: npm run test

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check dist/
        run: git diff --exit-code dist/

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['2019', 'latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install TeX Live
        uses: ./
        with:
          version: ${{ matrix.version }}
          cache: false

      - name: Test
        run: tlmgr --version
