name: CI
on:
  push:
    branches: main
  workflow_call:
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [build, format-check, lint, test]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run ${{ matrix.script }}
      - if: github.event_name == 'push' && matrix.script == 'test'
        uses: codecov/codecov-action@v3
  test:
    if: github.event_name == 'push'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
      - run: tlmgr --version
