name: Dependabot

on:
  workflow_run:
    workflows:
      - Pull request
    types:
      - completed

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.sender.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          fetch-depth: 0

      - name: Try to merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge -md || true
