name: E2E Historic
on:
  workflow_dispatch:
    inputs:
      os:
        description: OS (ubuntu, windows, macos)
        type: string
        required: false
      version:
        description: TeX Live version
        type: string
        required: false
permissions:
  contents: read
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - if: github.actor == 'nektos/act'
        name: Install jq
        run: |
          apt update
          apt install -y --no-install-recommends jq
      - name: Generate matrix
        id: generate
        run: |
          ./scripts/generate-matrix.jq packages/data/data/texlive-versions.json |
          tee -a "${GITHUB_OUTPUT}"
        env:
          os: ${{ inputs.os }}
          version: ${{ inputs.version }}
  historic:
    needs: generate-matrix
    strategy:
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
      max-parallel: 4
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
          version: ${{ matrix.version }}
