name: E2E Runners
#
# Tests on GitHub hosted runners[^1]
# - including runners in public preview, but
# - excluding the `-latest` runners.
#
# The `-latest` runners are tested in a separate workflow file[^2].
#
# [^1]: <https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories>
# [^2]: <https://github.com/teatimeguest/setup-texlive-action/blob/main/.github/workflows/e2e.yml>
#
on: workflow_dispatch
permissions:
  contents: read
jobs:
  non-latest-runners:
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-2025
          - windows-2019
          - macos-15
          - macos-13
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
      - run: tlmgr version
