name: Test
on:
  push:
    branches: [main]
    paths:
      - 'dist/**'
      - '!**/*.md'
      - action.yml
  workflow_dispatch:
permissions:
  contents: read
jobs:
  non-latest-runners:
    if: github.actor != 'nektos/act'
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - windows-2019
          - macos-14
          - macos-13
          - macos-11
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
      - run: tlmgr version
  save-cache:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    outputs:
      ubuntu: ${{ steps.status.outputs.ubuntu || '' }}
      windows: ${{ steps.status.outputs.windows || '' }}
      macos: ${{ steps.status.outputs.macos || '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        id: setup
        uses: ./
      - if: fromJSON(steps.setup.outputs.cache-restored)
        run: exit 1
      - run: tlmgr version
      - name: Set output
        id: status
        shell: bash
        run: |
          echo "${MATRIX_OS}=${MATRIX_OS}" >> "${GITHUB_OUTPUT}"
        env:
          MATRIX_OS: ${{ matrix.os }}
  restore-cache:
    needs: save-cache
    if: ${{ !cancelled() }}
    strategy:
      matrix:
        os:
          - ${{ needs.save-cache.outputs.ubuntu }}
          - ${{ needs.save-cache.outputs.windows }}
          - ${{ needs.save-cache.outputs.macos }}
        exclude:
          - os: ''
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        id: setup
        uses: ./
      - if: ${{ !fromJSON(steps.setup.outputs.cache-hit) }}
        run: exit 1
      - run: tlmgr version
  delete-caches:
    needs: restore-cache
    if: >-
      always() &&
      github.actor != 'nektos/act'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            await require('./.github/delete-caches.cjs')({
              context,
              core,
              github,
            });
  install-packages:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: ./
        with:
          cache: false
          package-file: |
            **/tl_packages
            **/DEPENDS.txt
          packages: latex-bin
      - run: latex -version
